version: '3.8'
networks:
  default:
    name: elevator-network
services:
  db:
    container_name: elevator-api-database
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - database-data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  pgadmin:
    container_name: elevator-api-pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5050:80"
    volumes:
      - pgadmin:/root/.pgadmin
    depends_on:
    - db

  api:
    container_name: elevator-api
    image: elevator-network
    build:
      context: .
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "2020:2020"
    depends_on:
      - db
volumes:
  database-data:
  pgadmin: